// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // `prisma generate` runs in `postinstall` (every `npm ci`) and does NOT
    // connect to a DB — so it must not hard-require DATABASE_URL. Prisma's
    // `env()` helper throws when the var is missing (breaks CI / fresh clones
    // with no .env). Read it directly with a non-connecting placeholder
    // fallback instead; migrate/seed/deploy set the real DATABASE_URL.
    url:
      process.env.DATABASE_URL ??
      "postgresql://placeholder:placeholder@localhost:5432/placeholder",
  },
});
